import 'package:flutter/widgets.dart';

abstract final class CodeWorkspaceText {
  static const _values = <String, Map<String, String>>{
    'zh': {
      'files.title': '项目文件',
      'files.root': '项目根目录',
      'files.empty': '当前目录没有可查看的文件',
      'files.truncated': '文件较多，仅展示前 500 项',
      'files.editing': '正在编辑',
      'files.saved': '已保存',
      'files.unsaved': '未保存',
      'files.save': '保存文件',
      'files.saveSuccess': '文件已保存',
      'files.saveFailed': '文件保存失败',
      'files.unsavedTitle': '放弃未保存的修改？',
      'files.unsavedHint': '返回后，本次在手机上的修改将丢失。',
      'files.discard': '放弃修改',
      'files.keepEditing': '继续编辑',
      'files.copy': '复制内容',
      'files.copied': '文件内容已复制',
      'files.loadFailed': '文件加载失败',
      'files.operationFailed': '文件操作失败',
      'action.back': '返回',
      'action.parent': '上一级',
      'action.refresh': '刷新',
      'action.retry': '重试',
      'action.stop': '停止执行',
      'attention.title': '待我处理',
      'attention.viewAll': '查看全部',
      'attention.empty': '当前没有需要你处理的 Code 事项',
      'attention.loadFailed': '待处理事项加载失败',
      'attention.session': '开发会话 #{id}',
      'attention.confirmHint': '该操作会立即影响当前开发会话，是否继续？',
      'attention.cancel': '取消',
      'attention.confirm': '确认执行',
      'attention.actionSuccess': '操作已完成',
      'attention.actionFailed': '操作失败，请稍后重试',
      'attention.openFailed': '开发会话打开失败',
      'hub.title': '开发指挥台',
      'hub.sessions': '开发会话',
      'hub.projectTasks': '项目任务',
      'hub.sessionCount': '{count} 个',
      'hub.project': '当前项目',
      'hub.noProjectTasks': '当前项目还没有开发任务',
      'hub.noProjectTasksHint': '新建会话并发送第一条开发指令后，任务会显示在这里。',
      'hub.heroTitle': '随时掌握开发进度',
      'hub.heroDescription': '发指令、看过程、做审批，复杂操作留给桌面端。',
      'hub.all': '任务',
      'hub.active': '进行中',
      'hub.create': '新建',
      'hub.projectTerminal': '项目终端',
      'hub.projectTerminalHint': '直接进入项目目录，处理命令行操作和快速排查。',
      'terminal.chooseProject': '选择终端项目',
      'terminal.chooseProjectHint': '终端将在项目工作目录中启动，高风险命令仍需谨慎确认。',
      'terminal.noProjects': '还没有开发项目，请先在管理台创建项目。',
      'terminal.openFailed': '项目终端打开失败',
      'terminal.opening': '正在打开终端...',
      'terminal.projectTitle': '项目终端',
      'terminal.noTask': '暂无任务',
      'terminal.taskTitle': '任务 · {task}',
      'terminal.reconnect': '重新连接',
      'terminal.releaseControl': '释放终端控制',
      'terminal.takeControl': '接管终端',
      'terminal.sessionStatus': '会话状态与指令',
      'terminal.files': '文件',
      'terminal.commandHint': '输入命令，支持中文和长命令编辑',
      'terminal.disconnected': '终端未连接',
      'terminal.takeControlHint': '点输入框即可接管终端控制',
      'terminal.sendCommand': '发送命令',
      'terminal.historyPrevious': '↑历史',
      'terminal.historyNext': '↓历史',
      'terminal.paste': '粘贴',
      'terminal.nativeKeyboard': '终端键盘',
      'session.worktreeChecking': '正在检查隔离工作区...',
      'session.worktreeReady': '已启用隔离工作区',
      'session.worktreeReadyHint': '会话将在独立 Git Worktree 中运行，不直接修改项目主目录。',
      'session.worktreeDirty': '项目存在未提交变更',
      'session.worktreeDirtyHint': '请先在桌面端处理以下仓库，再创建开发会话：{repositories}',
      'session.worktreeUnavailable': '当前项目无法安全创建会话',
      'session.worktreeReason_not_git': '项目目录不是 Git 仓库，请先在桌面端完成仓库配置。',
      'session.worktreeReason_source_unavailable': '项目源码目录不可用，请先在桌面端检查项目配置。',
      'session.worktreeReason_unknown': '项目暂不支持 Git Worktree 隔离。',
      'session.worktreeCheckFailed': '隔离能力检查失败',
      'session.worktreeRetry': '重新检查',
      'stop.title': '停止当前开发任务？',
      'stop.description': '正在执行和排队中的指令会被停止，已产生的文件变更会保留。',
      'stop.cancel': '继续执行',
      'stop.confirm': '确认停止',
      'stop.success': '已发送停止请求',
      'delivery.title': '统一交付',
      'delivery.empty': '将当前会话变更合并到项目主分支并统一推送。',
      'delivery.unavailable': '当前会话没有受管隔离工作区，请新建支持 Git Worktree 的项目会话。',
      'delivery.start': '开始统一交付',
      'delivery.retry': '重新交付',
      'delivery.deliverLatest': '交付后续提交',
      'delivery.confirmTitle': '开始统一交付？',
      'delivery.confirmDescription':
          '系统会固化当前已保存提交，完成同步、合并、质量检查和推送。交付期间产生的后续提交会保留，可再次交付。',
      'delivery.cancel': '暂不交付',
      'delivery.confirm': '确认交付',
      'delivery.started': '统一交付已进入队列',
      'delivery.failed': '交付失败',
      'delivery.conflict': '检测到合并冲突',
      'delivery.conflictHint': '请先在电脑端打开该会话的隔离工作区，解决以下冲突并提交，再返回重试。',
      'delivery.completed': '已完成合并与推送',
      'delivery.pending': '待继续交付',
      'delivery.completedWithPending': '本批已交付，仍有后续提交待交付',
      'delivery.completedWithUnsaved': '本批已交付，后续修改尚未保存，请先在电脑端保存提交',
      'delivery.queued': '等待交付',
      'delivery.running': '正在交付',
      'delivery.queuePosition': '队列第 {position} 位',
      'delivery.attempt': '第 {attempt} 次尝试',
      'delivery.stageStoppingTerminal': '正在停止宿主终端',
      'delivery.stageSyncing': '正在同步远程分支',
      'delivery.stageMerging': '正在合并会话变更',
      'delivery.stageQualityCheck': '正在执行质量检查',
      'delivery.stagePushing': '正在推送主分支',
      'delivery.stageVerifying': '正在核验远端提交',
      'delivery.stageCleaning': '正在清理会话工作区',
    },
    'en': {
      'files.title': 'Project files',
      'files.root': 'Project root',
      'files.empty': 'No viewable files in this directory',
      'files.truncated': 'Only the first 500 items are shown',
      'files.editing': 'Editing',
      'files.saved': 'Saved',
      'files.unsaved': 'Unsaved',
      'files.save': 'Save file',
      'files.saveSuccess': 'File saved',
      'files.saveFailed': 'Failed to save file',
      'files.unsavedTitle': 'Discard unsaved changes?',
      'files.unsavedHint': 'Your mobile edits will be lost when you go back.',
      'files.discard': 'Discard',
      'files.keepEditing': 'Keep editing',
      'files.copy': 'Copy content',
      'files.copied': 'File content copied',
      'files.loadFailed': 'Failed to load files',
      'files.operationFailed': 'File operation failed',
      'action.back': 'Back',
      'action.parent': 'Parent folder',
      'action.refresh': 'Refresh',
      'action.retry': 'Retry',
      'action.stop': 'Stop execution',
      'attention.title': 'Needs attention',
      'attention.viewAll': 'View all',
      'attention.empty': 'No Code items need your attention',
      'attention.loadFailed': 'Failed to load attention items',
      'attention.session': 'Development session #{id}',
      'attention.confirmHint':
          'This action immediately affects the development session. Continue?',
      'attention.cancel': 'Cancel',
      'attention.confirm': 'Confirm',
      'attention.actionSuccess': 'Action completed',
      'attention.actionFailed': 'Action failed. Try again later.',
      'attention.openFailed': 'Failed to open the development session',
      'hub.title': 'Development command center',
      'hub.sessions': 'Development sessions',
      'hub.projectTasks': 'Project tasks',
      'hub.sessionCount': '{count}',
      'hub.project': 'Current project',
      'hub.noProjectTasks': 'No development tasks in this project',
      'hub.noProjectTasksHint':
          'Create a session and send the first instruction to add a task here.',
      'hub.heroTitle': 'Stay on top of development',
      'hub.heroDescription':
          'Send instructions, follow progress, and approve actions. Keep complex work on desktop.',
      'hub.all': 'Tasks',
      'hub.active': 'Active',
      'hub.create': 'New',
      'hub.projectTerminal': 'Project terminal',
      'hub.projectTerminalHint':
          'Open the project directory for command-line work and quick diagnostics.',
      'terminal.chooseProject': 'Choose a project',
      'terminal.chooseProjectHint':
          'The terminal starts in the project directory. Review high-risk commands carefully.',
      'terminal.noProjects':
          'No development projects yet. Create one in the admin console first.',
      'terminal.openFailed': 'Failed to open project terminal',
      'terminal.opening': 'Opening terminal...',
      'terminal.projectTitle': 'Project terminal',
      'terminal.noTask': 'No task',
      'terminal.taskTitle': 'Task · {task}',
      'terminal.reconnect': 'Reconnect',
      'terminal.releaseControl': 'Release terminal control',
      'terminal.takeControl': 'Take terminal control',
      'terminal.sessionStatus': 'Session status and instructions',
      'terminal.files': 'Files',
      'terminal.commandHint':
          'Type a command; long and composed input supported',
      'terminal.disconnected': 'Terminal disconnected',
      'terminal.takeControlHint': 'Tap the input to take terminal control',
      'terminal.sendCommand': 'Send command',
      'terminal.historyPrevious': '↑ History',
      'terminal.historyNext': '↓ History',
      'terminal.paste': 'Paste',
      'terminal.nativeKeyboard': 'Terminal keyboard',
      'session.worktreeChecking': 'Checking workspace isolation...',
      'session.worktreeReady': 'Isolated workspace enabled',
      'session.worktreeReadyHint':
          'This session runs in a separate Git Worktree without editing the project directory directly.',
      'session.worktreeDirty': 'Uncommitted changes detected',
      'session.worktreeDirtyHint':
          'Resolve these repositories on desktop before creating a session: {repositories}',
      'session.worktreeUnavailable':
          'This project cannot create a safe session',
      'session.worktreeReason_not_git':
          'The project directory is not a Git repository. Configure it on desktop first.',
      'session.worktreeReason_source_unavailable':
          'The project source directory is unavailable. Check its desktop configuration.',
      'session.worktreeReason_unknown':
          'Git Worktree isolation is unavailable for this project.',
      'session.worktreeCheckFailed': 'Workspace isolation check failed',
      'session.worktreeRetry': 'Check again',
      'stop.title': 'Stop the current Code task?',
      'stop.description':
          'Running and queued instructions will stop. Existing file changes are preserved.',
      'stop.cancel': 'Keep running',
      'stop.confirm': 'Stop',
      'stop.success': 'Stop request sent',
      'delivery.title': 'Unified delivery',
      'delivery.empty':
          'Merge this session into the project branch and push it through the managed delivery flow.',
      'delivery.unavailable':
          'This session has no managed worktree. Create a project session with Git Worktree support.',
      'delivery.start': 'Start delivery',
      'delivery.retry': 'Retry delivery',
      'delivery.deliverLatest': 'Deliver newer commits',
      'delivery.confirmTitle': 'Start unified delivery?',
      'delivery.confirmDescription':
          'GoPanel snapshots the saved commits, then syncs, merges, runs quality checks, and pushes. Newer commits remain available for another delivery.',
      'delivery.cancel': 'Not now',
      'delivery.confirm': 'Deliver',
      'delivery.started': 'Delivery queued',
      'delivery.failed': 'Delivery failed',
      'delivery.conflict': 'Merge conflicts detected',
      'delivery.conflictHint':
          'Open this session worktree on desktop, resolve and commit these conflicts, then retry here.',
      'delivery.completed': 'Merge and push completed',
      'delivery.pending': 'More commits pending',
      'delivery.completedWithPending':
          'This batch completed; newer commits are waiting for delivery',
      'delivery.completedWithUnsaved':
          'This batch completed; save the newer working tree changes on desktop first',
      'delivery.queued': 'Waiting for delivery',
      'delivery.running': 'Delivering',
      'delivery.queuePosition': 'Queue position {position}',
      'delivery.attempt': 'Attempt {attempt}',
      'delivery.stageStoppingTerminal': 'Stopping host terminals',
      'delivery.stageSyncing': 'Syncing the remote branch',
      'delivery.stageMerging': 'Merging session changes',
      'delivery.stageQualityCheck': 'Running quality checks',
      'delivery.stagePushing': 'Pushing the main branch',
      'delivery.stageVerifying': 'Verifying the remote commit',
      'delivery.stageCleaning': 'Cleaning the session workspace',
    },
  };

  static String t(BuildContext context, String key) {
    final language = View.of(context).platformDispatcher.locale.languageCode;
    return _values[language]?[key] ?? _values['en']![key] ?? key;
  }

  static String format(
    BuildContext context,
    String key,
    Map<String, Object> values,
  ) {
    var text = t(context, key);
    for (final entry in values.entries) {
      text = text.replaceAll('{${entry.key}}', entry.value.toString());
    }
    return text;
  }
}
