package router

import (
	"github.com/aihop/gopanel/app/api"
	"github.com/aihop/gopanel/app/middleware"
	"github.com/aihop/gopanel/constant"
	"github.com/aihop/gopanel/pkg/websocket"
	"github.com/gofiber/fiber/v3"
)

func CodeRouter(r fiber.Router) {
	group := r.Group("code")
	// Code 工作区使用 SUB_ADMIN 权限，确保普通管理员仍受目录沙箱限制。
	group.Use(middleware.JWT(constant.UserRoleSubAdmin))
	{
		// WebSocket 端点
		group.Get("/terminal", websocket.New(api.AIAgentWsSSH))
		group.Get("/executors", api.GetCodeExecutors)
		group.Get("/attention", api.GetCodeAttention)
		group.Get("/git/credentials", api.GetCodeGitCredentials)
		group.Post("/git/credentials", api.SaveCodeGitCredential)
		group.Put("/git/credentials/:id", api.SaveCodeGitCredential)
		group.Post("/git/credentials/verify", api.VerifyCodeGitCredential)
		group.Delete("/git/credentials/:id", api.DeleteCodeGitCredential)

		// Projects APIs
		group.Get("/projects", api.GetAIProjects)
		group.Post("/projects/repositories/discover", api.DiscoverCodeProjectRepositories)
		group.Post("/projects/quality-checks/preflight", api.PreflightCodeProjectQualityChecks)
		group.Post("/projects", api.CreateAIProject)
		group.Put("/projects/:id", api.UpdateAIProject)
		group.Get("/projects/:id/overview", api.GetCodeProjectOverview)
		group.Get("/projects/:id/git/branches", api.GetCodeProjectBranches)
		group.Delete("/projects/:id/git/branches", api.DeleteCodeProjectBranch)
		group.Get("/projects/:id/git/sync", api.GetCodeProjectSync)
		group.Post("/projects/:id/git/sync", api.SyncCodeProject)
		group.Post("/projects/:id/git/commit", api.CommitCodeProjectChanges)
		group.Get("/projects/:id/worktree-capability", api.GetCodeWorktreeCapability)
		group.Get("/ai-accounts", api.GetAIProviderAccounts)
		group.Post("/ai-accounts", api.SaveAIProviderAccount)
		group.Put("/ai-accounts/:id", api.SaveAIProviderAccount)
		group.Delete("/ai-accounts/:id", api.DeleteAIProviderAccount)
		group.Get("/system-diagnostics/state", api.GetSystemDiagnosticState)
		group.Post("/system-diagnostics/chat", api.ChatSystemDiagnostic)
		group.Get("/memory/setting", api.GetCodeMemorySetting)
		group.Put("/memory/setting", api.SaveCodeMemorySetting)
		group.Get("/memories", api.GetCodeMemories)
		group.Post("/memories", api.CreateCodeMemory)
		group.Delete("/memories/:id", api.DeleteCodeMemory)
		group.Put("/memory/summary", api.SaveCodeMemorySummary)
		group.Delete("/memory/summary", api.DeleteCodeMemorySummary)
		group.Get("/memory/audit-events", api.GetCodeMemoryAuditEvents)
		group.Get("/sessions/:id/memory/status", api.GetCodeSessionMemoryStatus)
		group.Post("/sessions/:id/memory/extract", api.ExtractCodeSessionMemory)
		group.Get("/worktree-residues", api.GetCodeWorktreeResidues)
		group.Post("/worktree-residues/cleanup", api.CleanupCodeWorktreeResidues)
		group.Post("/projects/:id/terminal", api.OpenCodeProjectTerminal)
		group.Get("/project-terminal/:id/ws", middleware.HostTerminalSameOrigin, websocket.New(api.HostTerminalWebSocket))
		group.Get("/projects/:id/database-accesses", api.GetCodeDatabaseAccesses)
		group.Put("/projects/:id/database-accesses", api.SaveCodeDatabaseAccess)
		group.Delete("/projects/:id/database-accesses/:accessId", api.DeleteCodeDatabaseAccess)

		// Dev Sessions APIs
		group.Get("/sessions", api.GetAISessions)
		group.Get("/sessions/:id", api.GetAISession)
		group.Get("/sessions/:id/history", api.GetCodeSessionHistory)
		group.Get("/runs/:id", api.GetCodeExecutionRun)
		group.Get("/sessions/:id/previews", api.GetAISessionPreviews)
		group.Post("/sessions", api.CreateAISession)
		group.Get("/sessions/:id/initialization", api.GetCodeSessionInitialization)
		group.Post("/sessions/:id/initialization/retry", api.RetryCodeSessionInitialization)
		group.Put("/sessions/:id/title", api.UpdateCodeSessionTitle)
		group.Put("/sessions/:id/approval-policy", api.UpdateCodeSessionApprovalPolicy)
		group.Post("/sessions/:id/instructions", api.CreateAISessionInstruction)
		group.Get("/sessions/:id/state", api.GetAISessionState)
		group.Get("/sessions/:id/structure", api.GetAISessionStructure)
		group.Get("/sessions/:id/file", api.GetAISessionFile)
		group.Put("/sessions/:id/file", api.SaveAISessionFile)
		group.Get("/sessions/:id/codex-runtime", api.GetCodexRuntimeState)
		group.Get("/sessions/:id/token-usage", api.GetCodeTokenUsage)
		group.Get("/sessions/:id/audit-events", api.GetCodeAuditEvents)
		group.Get("/sessions/:id/git/status", api.GetCodeGitStatus)
		group.Post("/sessions/:id/git/sync/check", api.CheckCodeSessionGitSync)
		group.Post("/sessions/:id/git/sync", api.SyncCodeSessionGitRepository)
		group.Get("/sessions/:id/git/diff", api.GetCodeGitDiff)
		group.Get("/sessions/:id/git/history", api.GetCodeGitHistory)
		group.Get("/sessions/:id/git/history/diff", api.GetCodeGitHistoryDiff)
		group.Put("/sessions/:id/git/stage", api.UpdateCodeGitStage)
		group.Post("/sessions/:id/git/commit", api.CommitCodeGitChanges)
		group.Post("/sessions/:id/git/save", api.SaveCodeGitChanges)
		group.Post("/sessions/:id/worktree/merge", api.MergeCodeSessionWorktree)
		group.Get("/sessions/:id/delivery", api.GetCodeDeliveryJob)
		group.Get("/sessions/:id/delivery/conflicts", api.GetCodeDeliveryConflicts)
		group.Get("/sessions/:id/delivery/conflicts/file", api.GetCodeDeliveryConflictFile)
		group.Put("/sessions/:id/delivery/conflicts/file", api.SaveCodeDeliveryConflictFile)
		group.Post("/sessions/:id/delivery/conflicts/complete", api.CompleteCodeDeliveryConflicts)
		group.Post("/sessions/:id/delivery/conflicts/manual-confirm", api.ConfirmManualCodeDeliveryConflict)
		group.Post("/sessions/:id/delivery/local-sync", api.SyncCodeSessionDeliveryLocal)
		group.Get("/sessions/:id/delivery/push", api.GetCodeDeliveryPushStatus)
		group.Post("/sessions/:id/delivery/push", api.PushCodeSessionDelivery)
		group.Post("/sessions/:id/delivery/revert", api.RevertCodeSessionDelivery)
		group.Post("/sessions/:id/database-query", api.ExecuteCodeDatabaseQuery)
		group.Get("/sessions/:id/quality-checks", api.GetCodeQualityChecks)
		group.Post("/sessions/:id/quality-checks/run", api.RunCodeQualityCheck)
		group.Post("/sessions/:id/stop", api.StopCodeSessionExecution)
		group.Post("/instructions/:id/retry", api.RetryCodeInstruction)
		group.Get("/approvals", api.GetAIApprovals)
		group.Post("/approvals/:id/approve", api.ApproveAIApproval)
		group.Post("/approvals/:id/reject", api.RejectAIApproval)

		// Tasks APIs
		group.Get("/desktop-summary", api.GetCodeDesktopSummary)
		group.Get("/tasks", api.GetAITasks)
		group.Get("/tasks/:id/messages", api.GetAITaskMessages)
		group.Put("/tasks/:id", api.UpdateAITask)
		group.Delete("/tasks/:id", api.DeleteAITask)
	}
}
