export function codeFileIcon(path: string, isDir = false) {
	if (isDir) return { name: "mdi:folder-outline" }
	const name = path.replaceAll("\\", "/").split("/").pop()?.toLowerCase() || ""
	const special = specialFileIcons[name]
	if (special) return special
	const extension = name.includes(".") ? name.slice(name.lastIndexOf(".") + 1) : ""
	return extensionIcons[extension] || { name: "mdi:file-outline" }
}

const specialFileIcons: Record<string, { name: string; color?: string }> = {
	dockerfile: { name: "mdi:docker", color: "#2496ed" },
	makefile: { name: "mdi:file-cog-outline" },
	"license": { name: "mdi:certificate-outline" },
	"readme": { name: "mdi:book-open-outline" },
	"readme.md": { name: "mdi:language-markdown-outline", color: "#5b8def" },
	".gitignore": { name: "mdi:git", color: "#f05133" },
	".dockerignore": { name: "mdi:docker", color: "#2496ed" },
	".env": { name: "mdi:cog-outline" },
	"package.json": { name: "mdi:npm", color: "#cb3837" },
	"tsconfig.json": { name: "mdi:language-typescript", color: "#3178c6" },
	"go.mod": { name: "mdi:language-go", color: "#00add8" },
	"go.sum": { name: "mdi:language-go", color: "#00add8" },
	"cargo.toml": { name: "mdi:language-rust", color: "#dea584" },
	"pubspec.yaml": { name: "mdi:language-dart", color: "#0175c2" },
}

const extensionIcons: Record<string, { name: string; color?: string }> = {
	vue: { name: "mdi:vuejs", color: "#42b883" },
	ts: { name: "mdi:language-typescript", color: "#3178c6" },
	tsx: { name: "mdi:language-typescript", color: "#3178c6" },
	js: { name: "mdi:language-javascript", color: "#c4a000" },
	jsx: { name: "mdi:language-javascript", color: "#c4a000" },
	mjs: { name: "mdi:language-javascript", color: "#c4a000" },
	cjs: { name: "mdi:language-javascript", color: "#c4a000" },
	go: { name: "mdi:language-go", color: "#00add8" },
	py: { name: "mdi:language-python", color: "#3776ab" },
	rs: { name: "mdi:language-rust", color: "#dea584" },
	java: { name: "mdi:language-java", color: "#e76f00" },
	kt: { name: "mdi:language-kotlin", color: "#7f52ff" },
	dart: { name: "mdi:language-dart", color: "#0175c2" },
	php: { name: "mdi:language-php", color: "#777bb4" },
	rb: { name: "mdi:language-ruby", color: "#cc342d" },
	swift: { name: "mdi:language-swift", color: "#f05138" },
	c: { name: "mdi:language-c", color: "#5c6bc0" },
	h: { name: "mdi:language-c", color: "#5c6bc0" },
	cpp: { name: "mdi:language-cpp", color: "#004482" },
	cc: { name: "mdi:language-cpp", color: "#004482" },
	cxx: { name: "mdi:language-cpp", color: "#004482" },
	hpp: { name: "mdi:language-cpp", color: "#004482" },
	cs: { name: "mdi:language-csharp", color: "#512bd4" },
	html: { name: "mdi:language-html5", color: "#e44d26" },
	htm: { name: "mdi:language-html5", color: "#e44d26" },
	css: { name: "mdi:language-css3", color: "#1572b6" },
	scss: { name: "mdi:sass", color: "#cd6799" },
	sass: { name: "mdi:sass", color: "#cd6799" },
	less: { name: "mdi:language-css3", color: "#1d365d" },
	json: { name: "mdi:code-json", color: "#cb8c00" },
	yaml: { name: "mdi:code-json", color: "#cb8c00" },
	yml: { name: "mdi:code-json", color: "#cb8c00" },
	toml: { name: "mdi:file-cog-outline" },
	xml: { name: "mdi:file-xml-box", color: "#e34f26" },
	md: { name: "mdi:language-markdown-outline", color: "#5b8def" },
	mdx: { name: "mdi:language-markdown-outline", color: "#5b8def" },
	sql: { name: "mdi:database-outline", color: "#336791" },
	sh: { name: "mdi:bash" },
	bash: { name: "mdi:bash" },
	zsh: { name: "mdi:bash" },
	svg: { name: "mdi:svg", color: "#ffb13b" },
	png: { name: "mdi:file-image-outline", color: "#5b8def" },
	jpg: { name: "mdi:file-image-outline", color: "#5b8def" },
	jpeg: { name: "mdi:file-image-outline", color: "#5b8def" },
	gif: { name: "mdi:file-image-outline", color: "#5b8def" },
	webp: { name: "mdi:file-image-outline", color: "#5b8def" },
	ico: { name: "mdi:file-image-outline", color: "#5b8def" },
	pdf: { name: "mdi:file-pdf-box", color: "#e5252a" },
	zip: { name: "mdi:folder-zip-outline" },
	gz: { name: "mdi:folder-zip-outline" },
	tgz: { name: "mdi:folder-zip-outline" },
	tar: { name: "mdi:folder-zip-outline" },
	txt: { name: "mdi:file-document-outline" },
	log: { name: "mdi:file-document-outline" },
	lock: { name: "mdi:lock-outline" },
}
